# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.BigIntegerField(default=1)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Date')),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Hour'),
        ),
        migrations.AddField(
            model_name='entry',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Website'),
        ),
        migrations.AlterUniqueTogether(
            name='date',
            unique_together=set([('year', 'month')]),
        ),
    ]
