# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='hits',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='date',
            unique_together=set([('year', 'month', 'day')]),
        ),
    ]
